# Generated by Django 4.2 on 2023-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='fullname',
        ),
        migrations.AddField(
            model_name='sports',
            name='fname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='sports',
            name='lname',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
