# Generated by Django 4.2 on 2023-05-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_sports_fullname_sports_fname_sports_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sports',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
