# Generated by Django 4.2 on 2023-05-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_project_delete_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_user',
        ),
        migrations.AlterField(
            model_name='project',
            name='delete_status',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
