# Generated by Django 4.2 on 2023-05-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_project_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='create_user',
        ),
    ]
