# Generated by Django 4.2 on 2023-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_project_create_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='create_user',
            new_name='users',
        ),
    ]
