# Generated by Django 4.2 on 2023-05-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_rename_create_user_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='create_user',
        ),
    ]
