# Generated by Django 4.2 on 2023-05-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0019_rename_users_project_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projecttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('delete_status', models.CharField(default='0', max_length=2)),
                ('create_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
