# Generated by Django 4.2 on 2023-05-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_alter_customers_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
