# Generated by Django 4.2 on 2023-05-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttable',
            name='categories',
            field=models.ManyToManyField(to='members.category'),
        ),
    ]
