# Generated by Django 4.2 on 2023-06-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0037_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialpurchase',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.party'),
        ),
    ]
