# Generated by Django 4.2 on 2023-06-12 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_alter_materialpurchase_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpurchase',
            name='project',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='members.projecttable'),
        ),
        migrations.AddField(
            model_name='materialpurchaseitem',
            name='project',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='members.projecttable'),
        ),
    ]
