# Generated by Django 4.2 on 2023-06-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_alter_materialpurchase_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpurchase',
            name='delete_status',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='materialpurchaseitem',
            name='delete_status',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
