# Generated by Django 4.2 on 2023-06-14 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0043_materialpurchase_delete_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Used',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveBigIntegerField()),
                ('notes', models.CharField(max_length=255)),
                ('delete_status', models.CharField(default='0', max_length=2)),
                ('materialpurchaseitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.materialpurchaseitem')),
            ],
        ),
    ]
