# Generated by Django 4.2 on 2023-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_alter_used_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
